export const sprintAnalyticsData = [
  {
    sprint: 'Sprint 1',
    durationDays: 10,
    developers: [
      {
        name: 'Jose Emilio',
        completedTasks: 8,
        assignedTasks: 10,
        realHours: 33,
        completedStoryPoints: 21,
        leadTimeHours: 16,
        taskActivityActions: 18,
        botReactionTimeMinutes: 4.1,
      },
      {
        name: 'Arturo',
        completedTasks: 7,
        assignedTasks: 9,
        realHours: 29,
        completedStoryPoints: 18,
        leadTimeHours: 15,
        taskActivityActions: 16,
        botReactionTimeMinutes: 3.8,
      },
      {
        name: 'Yael',
        completedTasks: 6,
        assignedTasks: 8,
        realHours: 27,
        completedStoryPoints: 16,
        leadTimeHours: 14,
        taskActivityActions: 14,
        botReactionTimeMinutes: 4.4,
      },
      {
        name: 'Andres',
        completedTasks: 5,
        assignedTasks: 7,
        realHours: 23,
        completedStoryPoints: 13,
        leadTimeHours: 13,
        taskActivityActions: 12,
        botReactionTimeMinutes: 4.9,
      },
      {
        name: 'Patricio',
        completedTasks: 6,
        assignedTasks: 8,
        realHours: 25,
        completedStoryPoints: 15,
        leadTimeHours: 14,
        taskActivityActions: 15,
        botReactionTimeMinutes: 4.3,
      },
    ],
    activeUsers: 5,
  },
  {
    sprint: 'Sprint 2',
    durationDays: 10,
    developers: [
      {
        name: 'Jose Emilio',
        completedTasks: 7,
        assignedTasks: 9,
        realHours: 31,
        completedStoryPoints: 19,
        leadTimeHours: 15,
        taskActivityActions: 15,
        botReactionTimeMinutes: 3.6,
      },
      {
        name: 'Arturo',
        completedTasks: 9,
        assignedTasks: 10,
        realHours: 36,
        completedStoryPoints: 25,
        leadTimeHours: 13,
        taskActivityActions: 23,
        botReactionTimeMinutes: 3.0,
      },
      {
        name: 'Yael',
        completedTasks: 5,
        assignedTasks: 8,
        realHours: 22,
        completedStoryPoints: 14,
        leadTimeHours: 16,
        taskActivityActions: 11,
        botReactionTimeMinutes: 4.5,
      },
      {
        name: 'Andres',
        completedTasks: 4,
        assignedTasks: 7,
        realHours: 20,
        completedStoryPoints: 11,
        leadTimeHours: 17,
        taskActivityActions: 10,
        botReactionTimeMinutes: 4.8,
      },
      {
        name: 'Patricio',
        completedTasks: 8,
        assignedTasks: 9,
        realHours: 30,
        completedStoryPoints: 20,
        leadTimeHours: 14,
        taskActivityActions: 19,
        botReactionTimeMinutes: 3.4,
      },
    ],
    activeUsers: 5,
  },
  {
    sprint: 'Sprint 3',
    durationDays: 10,
    developers: [
      {
        name: 'Jose Emilio',
        completedTasks: 6,
        assignedTasks: 8,
        realHours: 28,
        completedStoryPoints: 17,
        leadTimeHours: 16,
        taskActivityActions: 13,
        botReactionTimeMinutes: 3.7,
      },
      {
        name: 'Arturo',
        completedTasks: 5,
        assignedTasks: 8,
        realHours: 34,
        completedStoryPoints: 15,
        leadTimeHours: 19,
        taskActivityActions: 18,
        botReactionTimeMinutes: 4.0,
      },
      {
        name: 'Yael',
        completedTasks: 8,
        assignedTasks: 9,
        realHours: 27,
        completedStoryPoints: 23,
        leadTimeHours: 12,
        taskActivityActions: 17,
        botReactionTimeMinutes: 3.2,
      },
      {
        name: 'Andres',
        completedTasks: 7,
        assignedTasks: 9,
        realHours: 26,
        completedStoryPoints: 19,
        leadTimeHours: 13,
        taskActivityActions: 16,
        botReactionTimeMinutes: 3.5,
      },
      {
        name: 'Patricio',
        completedTasks: 8,
        assignedTasks: 10,
        realHours: 32,
        completedStoryPoints: 22,
        leadTimeHours: 14,
        taskActivityActions: 20,
        botReactionTimeMinutes: 3.3,
      },
    ],
    activeUsers: 5,
  },
];

export const ALL_SPRINTS_VALUE = 'All Sprints';
