apiVersion: v1
kind: Service
metadata:
  name: todolistapp-springboot-service
  annotations:
    oci.oraclecloud.com/loadbalancer-policy: "IP_HASH"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local

  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: todolistapp-springboot
---
apiVersion: v1
kind: Service
metadata:
  name: todolistapp-backend-router
spec:
  selector:
    app: todolistapp-springboot
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolistapp-springboot-deployment
spec:
  selector:
    matchLabels:
      app: todolistapp-springboot
  replicas: 2
  template:
    metadata:
      labels:
        app: todolistapp-springboot
        version: v1
    spec:
      containers:
        - name: todolistapp-springboot
          image: %DOCKER_REGISTRY%/todolistapp-springboot:0.1
          imagePullPolicy: Always
          env:
            - name: DB_URL
              value: "jdbc:oracle:thin:@%TODO_PDB_NAME%_tp?TNS_ADMIN=/wallet"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: jwt-secret
            - name: JWT_EXPIRATION_MS
              value: "86400000"
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: telegram-bot-token
            - name: TELEGRAM_BOT_USERNAME
              value: "%TELEGRAM_BOT_USERNAME%"
            - name: OCI_REGION
              value: "%OCI_REGION%"
          volumeMounts:
            - name: creds
              mountPath: /wallet
          ports:
            - containerPort: 8080
      restartPolicy: Always
      volumes:
        - name: creds
          secret:
            secretName: db-wallet-secret
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: todolistapp-springboot
---
