CREATE TABLE TODOITEM (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITLE VARCHAR2(180),
    DESCRIPTION VARCHAR2(4000),
    ASSIGNEE VARCHAR2(180),
    COMPLEXITY VARCHAR2(30),
    SPRINT VARCHAR2(180),
    REAL_HOURS NUMBER(10, 2),
    COMPLETED_AT TIMESTAMP WITH TIME ZONE,
    CREATION_TS TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    START_TIME TIMESTAMP WITH TIME ZONE,
    END_TIME TIMESTAMP WITH TIME ZONE,
    DONE NUMBER(1, 0) DEFAULT 0
);

CREATE TABLE USERS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PHONENUMBER VARCHAR2(30),
    PASSWORD VARCHAR2(100)
);

CREATE TABLE APP_USER (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FULL_NAME VARCHAR2(180) NOT NULL,
    EMAIL VARCHAR2(180) NOT NULL UNIQUE,
    IS_ACTIVE NUMBER(1, 0) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE PROJECT (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PROJECT_NAME VARCHAR2(180) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    STATUS VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL,
    MANAGER_ID NUMBER NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT FK_PROJECT_MANAGER FOREIGN KEY (MANAGER_ID) REFERENCES APP_USER (ID)
);

CREATE TABLE PROJECT_MEMBER (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PROJECT_ID NUMBER NOT NULL,
    USER_ID NUMBER NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT FK_PROJECT_MEMBER_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (ID),
    CONSTRAINT FK_PROJECT_MEMBER_USER FOREIGN KEY (USER_ID) REFERENCES APP_USER (ID)
);

CREATE TABLE SPRINT (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PROJECT_ID NUMBER NOT NULL,
    SPRINT_NAME VARCHAR2(180) NOT NULL,
    GOAL VARCHAR2(500),
    START_DATE DATE,
    END_DATE DATE,
    STATUS VARCHAR2(30) DEFAULT 'PLANNING' NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT FK_SPRINT_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (ID)
);

CREATE TABLE TASK (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PROJECT_ID NUMBER NOT NULL,
    SPRINT_ID NUMBER,
    TASK_NAME VARCHAR2(180) NOT NULL,
    DESCRIPTION VARCHAR2(1000),
    STATUS VARCHAR2(30) DEFAULT 'TODO' NOT NULL,
    PRIORITY VARCHAR2(30) DEFAULT 'MEDIUM' NOT NULL,
    STORY_POINTS NUMBER(10, 2),
    REAL_HOURS NUMBER(10, 2),
    ASSIGNED_TO_ID NUMBER,
    CREATED_BY_ID NUMBER NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE,
    COMPLETED_AT TIMESTAMP WITH TIME ZONE,
    CONSTRAINT FK_TASK_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (ID),
    CONSTRAINT FK_TASK_SPRINT FOREIGN KEY (SPRINT_ID) REFERENCES SPRINT (ID),
    CONSTRAINT FK_TASK_ASSIGNED_TO FOREIGN KEY (ASSIGNED_TO_ID) REFERENCES APP_USER (ID),
    CONSTRAINT FK_TASK_CREATED_BY FOREIGN KEY (CREATED_BY_ID) REFERENCES APP_USER (ID)
);

INSERT INTO TODOITEM (TITLE, DESCRIPTION, DONE)
VALUES ('Manual item insert', 'Seed item created during schema setup', 0);

COMMIT;
